version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: script_library
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_SECURE: false
      SMTP_USER: your_smtp_user
      SMTP_PASS: your_smtp_pass
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: script_library
    ports:
      - "3306:3306"
